// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNhcfUOLDX9dAVeSCH4WKcyjCWUwuaRJ8',
    appId: '1:969900702891:web:616b2e90abc472e5034bee',
    messagingSenderId: '969900702891',
    projectId: 'clauseai-3f7de',
    authDomain: 'clauseai-3f7de.firebaseapp.com',
    storageBucket: 'clauseai-3f7de.firebasestorage.app',
    measurementId: 'G-616JE6FWRC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8DkCT-V5vZ8EcOTOjdFQ3rx1n9vCPgOo',
    appId: '1:969900702891:android:b737637a2a241848034bee',
    messagingSenderId: '969900702891',
    projectId: 'clauseai-3f7de',
    storageBucket: 'clauseai-3f7de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi19aCb1nudKnmhdSqbdaOlJWfd9iQEYk',
    appId: '1:969900702891:ios:eaa059e932c8731f034bee',
    messagingSenderId: '969900702891',
    projectId: 'clauseai-3f7de',
    storageBucket: 'clauseai-3f7de.firebasestorage.app',
    iosBundleId: 'com.example.dealInsightsAssistant',
  );

}